### ISSUE TITLE
Error handling for SIL Parser

### ISSUE THREAD

**Issue by albertocasagrande** [dreossi/sapo#7]
The SIL parser sometimes fails to report errors or provide a useful description. For instance, no error arises when the symbols `?`, `'`, `_`, `@`, `Ç`, `$`, `%`, and `&` are present in the input: they are printed at the beginning of the output. You can reproduce this behavior by using [this](https://github.com/dreossi/sapo/files/7532203/model.txt) SIL file.

The parser also does not complain when two parameters are multiplied in the same term of the dynamics, such as in ```dynamics(s) = s - alpha*beta*s``` where `alpha` and `beta` are two parameters. However, in this case, Sapo ends its execution with a crash. See this bug in action on [this](https://github.com/dreossi/sapo/files/7532209/model.txt) input file.

**Comment by LucaDorigo** [comment]
I pushed a new version of the SIL parser that addresses this issue, and tries to provide useful information for many common errors a user can do.
Obviously, I had to make choices on which are the common errors, and how to try to inform the user.
If you think that these choices are good we can close the issue, otherwise let me know your ideas to make it better.
